%plot visualizations montage plots for correlation pos/neg of the factor
%variables

%% add montage plots for positive/negative correlations and sig components
%plot worry, and social disinterest (moodiness had no surviving components)
sigcomps_worry_pos = [1,2,3,4,6,7,27,30,33];  %Positive correlations
%9 positive

files = {...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,1',...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,2',...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,3',...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,4',...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,6',...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,7',....
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,27',...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,30',...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,33',...
}; 

% Display all components in ONE montage figure
icatb_image_viewer(files, ...
    'display_type','montage', ...
    'structfile', fullfile(fileparts(which('gift.m')), ...
    'icatb_templates','shrunk_single_subj_T1.nii'), ...
    'threshold', 5.0, ... 
    'slices_in_mm', (-60:8:60), ...
    'convert_to_zscores', 'yes', ...
    'image_values', 'positive', ...
    'iscomposite','yes');

title ('Significant positive correlations and the respective loading components for worry & rumination: FDR Corrected '); 
set(gca, 'FontSize', 13);

% Save the figure
savefig('AllComponents_Worry_Rum_PositiveCorrs_FDR_Corrected.fig');

%% plot negative correlations
sigcomps_worry_neg = [12,14,15,26,36,39,41,44,55];  %Positive correlations
%9 negative
files = {...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,12',...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,14',...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,15',...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,26',...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,36',...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,39',....
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,41',...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,44',...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,55',...

}; 

% Display all components in ONE montage figure
icatb_image_viewer(files, ...
    'display_type','montage', ...
    'structfile', fullfile(fileparts(which('gift.m')), ...
    'icatb_templates','shrunk_single_subj_T1.nii'), ...
    'threshold', 5.0, ... 
    'slices_in_mm', (-60:8:60), ...
    'convert_to_zscores', 'yes', ...
    'image_values', 'positive', ...
    'iscomposite','yes');

title ('Significant negative correlations and respective loadings for worry & rumination: FDR Corrected '); 
set(gca, 'FontSize', 13);

% Save the figure
savefig('AllComponents_Worry_Rum_NegativeCorrs_FDR_Corrected.fig');
%% next, plot for social disinterest
sigcomps_socialdis_pos = [3,7,26,47,68]; 
%5 components

files = {...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,3',...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,7',...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,26',...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,47',...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,68',...
}; 
% Display all components in ONE montage figure
icatb_image_viewer(files, ...
    'display_type','montage', ...
    'structfile', fullfile(fileparts(which('gift.m')), ...
    'icatb_templates','shrunk_single_subj_T1.nii'), ...
    'threshold', 5.0, ... 
    'slices_in_mm', (-60:8:60), ...
    'convert_to_zscores', 'yes', ...
    'image_values', 'positive', ...
    'iscomposite','yes');

title ('Significant positive correlations and its respective loadings for social disinterest: FDR Corrected '); 
set(gca, 'FontSize', 13);

% Save the figure
savefig('AllComponents_SocialDis_PositiveCorrs_FDR_Corrected.fig');

%% plot negative correlations
sigcomps_socialdis_neg = 55; 
files = cell(1, numel(sigcomps_socialdis_neg));
for i = 1:numel(sigcomps_socialdis_neg)
    files{i} = sprintf('Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,%d', comps(i));
end

% Display all components in ONE montage figure
icatb_image_viewer(files, ...
    'display_type','montage', ...
    'structfile', fullfile(fileparts(which('gift.m')), ...
    'icatb_templates','shrunk_single_subj_T1.nii'), ...
    'threshold', 5.0, ... 
    'slices_in_mm', (-60:8:60), ...
    'convert_to_zscores', 'yes', ...
    'image_values', 'positive', ...
    'iscomposite','yes');

title ('Significant negative correlations and its respective loadings for social disinterest: FDR Corrected '); 
set(gca, 'FontSize', 13);

% Save the figure
savefig('AllComponents_SocialDis_NegativeCorrs_FDR_Corrected.fig');
