%%  Spatial_Component_Visualization_FDR_Corrected.m to view these sorted components from the loading parameter analysis
%previous scripts cleaned p and q values, labelled per NM 2.2 domain and
%subdomain, then sorted by domain and subdomain for visualization purposes
%Load SPECT_CoM_Workspace 
% get into the right path first
cd  '/Users/amrithah/Desktop/CalhounLab/Dissertation/Projects/Chapter7_Paper_6_Diss_Clinical_Outcomes/ICA_Results/Depression_ICA_Analyses_Clinical_Outcomes'
%% Plot significant q values from bar plot from the SPECT SZ analysis here
%all 35 components plotted together; split by positive and negative within
%the 35 significant components
% Ordered list of components, q vals that were significant
     
%%  plot positive and negative components as montage plots
%first 19 positive
% Build file list
files = { ...

'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,9', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,14', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,16', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,17', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,18', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,19', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,21', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,22', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,25', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,26', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,27', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,28', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,30', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,49', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,52', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,53', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,59', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,62', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,63' ...
};

% Display all components in ONE montage figure
icatb_image_viewer(files, ...
    'display_type','montage', ...
    'structfile', fullfile(fileparts(which('gift.m')), ...
    'icatb_templates','shrunk_single_subj_T1.nii'), ...
    'threshold', 5.0, ... 
    'slices_in_mm', (-60:8:60), ...
    'convert_to_zscores', 'yes', ...
    'image_values', 'positive', ...
    'iscomposite','yes');

title ('19 Significant Positive Components | HC > DEP : FDR Corrected Plotted '); 
set(gca, 'FontSize', 13);

% Save the figure
savefig('AllComponents_Positive_FDR_Corrected.fig');

%% now plot 16 negative components
% Build file list
files = {...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,2', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,6', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,15', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,29', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,32', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,33', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,36', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,38', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,41', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,50', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,54', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,56', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,58', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,65', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,66', ...
'Depression_ICA_Output_Rest_Clinical_Outcomes_Results_group_component_ica_.nii,68' ...
};

% Display all components in ONE montage figure
icatb_image_viewer(files, ...
    'display_type','montage', ...
    'structfile', fullfile(fileparts(which('gift.m')), ...
    'icatb_templates','shrunk_single_subj_T1.nii'), ...
    'threshold', 5.0, ... 
    'slices_in_mm', (-60:8:60), ...
    'convert_to_zscores', 'yes', ...
    'image_values', 'positive', ...
    'iscomposite','yes');

title ('16 Significant Negative Components | DEP > HC : FDR Corrected Plotted '); 
set(gca, 'FontSize', 13);

% Save the figure
savefig('AllComponents_Negative_FDR_Corrected.fig');